<a href="https://colab.research.google.com/github/noothankumar7618/assign_codes/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Numpy - Numerical Python
1. Allows several Mathematical operations.
2. Faster Operations.

In [3]:
# importing numpy library
import numpy as np           


List v/s Numpy - Time taken

In [4]:
# time is a library
from time import process_time

Time taken by a list


In [5]:
python_list=[i for i in range(10000)]

start_time=process_time()

python_list=[i+5 for i in python_list]

end_time=process_time()

print(end_time - start_time)

0.0007146909999999895


Time taken by a Numpy


In [6]:
np_array=np.array([i for i in range(10000)])

start_time=process_time()

np_array+=5

end_time=process_time()

print(end_time - start_time)

0.0002566389999998364


Numpy Arrays

In [7]:
#list
list1=[1,2,3,4,5]
print(list1)
type(list1)

[1, 2, 3, 4, 5]


list

In [9]:
np_array=np.array([1,2,3,4,5])
print(np_array)
type(np_array)

[1 2 3 4 5]


numpy.ndarray

In [11]:
#creating a 1 dimentional array
a=np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [12]:
#Number of columns
a.shape

(5,)

In [15]:
#creating a 2 dimentional array
b=np.array([(1,2,3,4),(7,8,9,10)])
print(b)

[[ 1  2  3  4]
 [ 7  8  9 10]]


In [17]:
#Number of Rows and columns
b.shape

(2, 4)

In [19]:
#creating a 2 dimentional array with float
c=np.array([(1,2,3,4),(7,8,9,10)], dtype=float)
print(c)

[[ 1.  2.  3.  4.]
 [ 7.  8.  9. 10.]]


Initial Placeholders in Numpy Array


In [20]:
#Creating a numpy array of Zeros
x=np.zeros((4,6))
print(x)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [21]:
#Creating a numpy array of Ones
y=np.ones((4,6))
print(y)

[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


In [22]:
#creating a particular value
z=np.full((4,6),5)
print(z)

[[5 5 5 5 5 5]
 [5 5 5 5 5 5]
 [5 5 5 5 5 5]
 [5 5 5 5 5 5]]


In [23]:
#Creating an identity matrix
p=np.eye(5)
print(p)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [24]:
#Create a numpy array with random values
q=np.random.random((3,4))
print(q)

[[0.71764889 0.36378493 0.87413703 0.17072031]
 [0.96163143 0.81095622 0.77457035 0.77140894]
 [0.22172929 0.31072906 0.35713784 0.66823995]]


In [28]:
# random integer values array within a specific range
r=np.random.randint(10,100,(3,5))
print(r)

[[84 11 67 82 81]
 [25 42 91 59 42]
 [77 62 78 55 46]]


In [29]:
#array of evenly spaced values -->specifying number of values required
d=np.linspace(10,30,5)
print(d)

[10. 15. 20. 25. 30.]


In [31]:
#array of evenly spaced values -->specifying the step
d=np.arange(10,30,5)
print(d)

[10 15 20 25]


In [32]:
#Convert a list to a numpy array
list2=[1,4,6,8,4,9]

np_array=np.asarray(list2)
print(np_array)
type(np_array)

[1 4 6 8 4 9]


numpy.ndarray

In [34]:
#Convert a tuple to a numpy array
tuple=(1,4,6,8,4,9)

np_array=np.asarray(tuple)
print(np_array)
type(np_array)

[1 4 6 8 4 9]


numpy.ndarray

Analysing a Numpy array


In [9]:
c=np.random.randint(10,100,(4,5))
print(c)

[[91 91 73 77 91]
 [66 42 52 83 35]
 [44 29 81 12 25]
 [71 27 21 33 68]]


In [39]:
#array dimension
print(c.shape)

(4, 5)


In [40]:
#number of dimensions
print(c.ndim)

2


In [10]:
#Number of elements in an array
print(c.size)

20


In [11]:
#Checking data types of the values in the array
print(c.dtype)

int64


Mathematical operations on a Numpy array


In [12]:
list1=[1,2,3,4,5]
list2=[6,7,8,9,10]

print(list1+list2)  #COncatenate or two joins

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [14]:
a=np.random.randint(0,10,(3,3))
b=np.random.randint(10,20,(3,3))
print(a)
print(b)

[[2 2 9]
 [8 2 9]
 [0 2 8]]
[[13 17 10]
 [12 12 14]
 [17 19 14]]


In [15]:
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[[15 19 19]
 [20 14 23]
 [17 21 22]]
[[-11 -15  -1]
 [ -4 -10  -5]
 [-17 -17  -6]]
[[ 26  34  90]
 [ 96  24 126]
 [  0  38 112]]
[[0.15384615 0.11764706 0.9       ]
 [0.66666667 0.16666667 0.64285714]
 [0.         0.10526316 0.57142857]]


In [17]:
#(OR)
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

[[15 19 19]
 [20 14 23]
 [17 21 22]]
[[-11 -15  -1]
 [ -4 -10  -5]
 [-17 -17  -6]]
[[ 26  34  90]
 [ 96  24 126]
 [  0  38 112]]
[[0.15384615 0.11764706 0.9       ]
 [0.66666667 0.16666667 0.64285714]
 [0.         0.10526316 0.57142857]]


Array Manipulation


In [18]:
array=np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[4 8 7]
 [7 9 1]]
(2, 3)


In [19]:
#Transpose
trans=np.transpose(array)
print(trans)
print(trans.shape)

[[4 7]
 [8 9]
 [7 1]]
(3, 2)


In [20]:
#(OR)
trans2=array.T
print(trans2)
print(trans2.shape)

[[4 7]
 [8 9]
 [7 1]]
(3, 2)


In [21]:
#Reshaping a array
a=np.random.randint(0,10,(2,3))
print(a)
print(a.shape)

[[7 7 1]
 [6 9 0]]
(2, 3)


In [22]:
b=a.reshape(3,2)
print(b)
print(b.shape)

[[7 7]
 [1 6]
 [9 0]]
(3, 2)
